### ISSUE TITLE
Spacebar as keybinding

### ISSUE THREAD

**Issue by retrography** [insanum/sncli#27]
Is there any way to bind spacebar to a function with the current configuration files?

**Comment by swalladge** [comment]
This wasn't previously possible due to configparser ignoring whitespace-only values (sets them to empty strings). Commit 44cc2b1 fixes this by allowing you to use the `space` keyword to bind spacebar to an action. See also the urwid [article on user input](http://urwid.org/manual/userinput.html#keyboard-input) for examples of how to format other keybindings. `tab` and `enter` work as well.

**Comment by retrography** [comment]
thanks!
