### ISSUE TITLE
support shadow socks proxy configuration

### ISSUE THREAD

**Issue by hatelove85911** [insanum/sncli#39]
my sncli client can't login due to the GFW of China, please help add support for socks proxy.

**Comment by swalladge** [comment]
It seems the Requests HTTP library we're using supports socks proxies directly (see http://docs.python-requests.org/en/master/user/advanced/#socks for more info). It should be doable - I'll investigate when I get some free time next.

**Comment by nbenm** [comment]
I use proxychains (socks5), and it works fine.

**Comment by swalladge** [comment]
@hatelove85911 We can't implement this as a configuration variable in sncli now, since we're using the simperium library for syncing. However this uses requests, and according to the [requests docs](https://2.python-requests.org//en/master/user/advanced/#proxies):

> You can also configure proxies by setting the environment variables HTTP_PROXY and HTTPS_PROXY.

You should be able to test and use this like:

```bash
export HTTPS_PROXY="http://my.proxy"
sncli
```

Put it in a shell script, or alias, or set the env var system-wide to use it automatically.
