### ISSUE TITLE
Saving files while in vim edit mode doesn't result in synch

### ISSUE THREAD

**Issue by jul-reb** [insanum/sncli#72]
Notes are only synched upon exiting, rather than saving, this made for an awkward situation where I saved my note, expecting it to be synched, but upon power loss I lost all of my work since the files are stored in /tmp/ and this automatically empties itself on most distros.

**Comment by swalladge** [comment]
Unfortunately this is unavoidable due to how different editors interact with the filename given. The only reliable way is to reread the file after the editor has exited. 

If you want the temporary files stored somewhere on-disk to survive a reboot or power loss, you can set the `cfg_tempdir` option to a custom directory.

Perhaps it would be worthwhile documenting this behaviour with a warning as well as the `cfg_tempdir` option in the readme or wiki?

**Comment by swalladge** [comment]
I'd rather document the `cfg_tempdir` option in the readme than change the default. The default is the simplest option and most effective for most cases.
